parameters:
  databricksbundle:
    databricks_connect:
      connection:
        address: 'https://dbc-123.cloud.databricks.com'
        token: 'abcd123456'
        cluster_id: '0416-084917-doles835'

  lineagebundle:
    notebooks:
      layer_pattern: '^%daipe.root_module.name%/{layer}'

  sqlalchemybundle:
    connections:
      default:
        engine: dummy
        host: 'foo.bar'
        database: 'mydatabase'
        username: 'root'
        password: 'pass123'
